push = require 'lib/push'
Class = require 'lib/class'

require 'src/constants'

require 'src/util'
require 'src/Animation'

require 'src/StateMachine'
require 'src/Entity'
require 'src/Object'
require 'src/Level'
require 'src/Tile'
require 'src/Snail'
require 'src/Player'
require 'src/states/BaseState'
require 'src/states/game/PlayState'
require 'src/states/game/StartState'
require 'src/states/player/PlayerIdleState'
require 'src/states/player/PlayerMovingState'
require 'src/states/player/PlayerJumpingState'
require 'src/states/player/PlayerFallingState'
require 'src/states/snail/SnailIdleState'
require 'src/states/snail/SnailDeadState'
require 'src/states/snail/SnailMovingState'
